### ISSUE TITLE
録画時のChinachuとの優先度変更

### ISSUE THREAD

**Issue by unlimish** [sogaani/Amumu#3]
Chinachuで録画が開始されたときに、Amumuがエンコードを行っている場合、Amumuでのエンコードの優先度を下げて、録画に影響が出ないようにする機能の実装を希望します。
その機能があると性能が良くないサーバーでも快適に使えるかと思われます。

**Comment by sogaani** [comment]
@oga6 こんにちは。
最初から優占度を下げて実行できるオプションをつけるのはいかがですか？
chinachuのAPIをポーリングすれば、録画状況に合わせて動的に変更することもできますが、root権限がなければ優占度を下げた後に再度上げることはできません。

**Comment by unlimish** [comment]
提案ありがとうございます。
確かに、はじめから優先度を下げた上で実行すれば問題ないですね。その方法で運用していこうと思います。
アドバイスありがとうございました！

**Comment by unlimish** [comment]
提案ありがとうございます。
確かに、はじめから優先度を下げた上で実行すれば問題ないですね。その方法で運用していこうと思います。
アドバイスありがとうございました！

**Comment by sogaani** [comment]
優占度の変更はffmpeg実行時または実行後にffmpegに対して行う必要がありますが、この機能は実装してくても大丈夫ですか？
もしご自身で修正する場合はプルリクエストも歓迎します。

**Comment by unlimish** [comment]
その点は自分で書けそうなので大丈夫です👍
このrepoの発展を期待してます！
